-- Empty-database schema for canonical catalog CSVs.
-- This intentionally uses numeric internal IDs. External Open Library keys live
-- in *_external_identifier tables and the transitional uuid columns.

SET client_min_messages = warning;
SET statement_timeout = 0;

CREATE TABLE work_creator (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    uuid varchar(255) NOT NULL,
    creator_name text,
    personal_name text,
    birth_date varchar(255),
    death_date varchar(255),
    ol_id varchar(100)
);

CREATE TABLE author_external_identifier (
    author_id bigint NOT NULL,
    provider varchar(50) NOT NULL,
    external_id varchar(255) NOT NULL,
    is_canonical boolean NOT NULL
);

CREATE TABLE author_alternate_name (
    author_id bigint NOT NULL,
    alternate_name text NOT NULL,
    position integer
);

CREATE TABLE author_external_link (
    author_id bigint NOT NULL,
    link_type varchar(50) NOT NULL,
    url text NOT NULL
);

CREATE TABLE prh_author_profile (
    author_id bigint NOT NULL,
    prh_author_id bigint NOT NULL,
    biography_html text,
    photo_url text,
    photo_credit text,
    photo_date varchar(100),
    prh_url text,
    reported_work_count bigint,
    related_links jsonb
);

CREATE TABLE quillent_work (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    uuid varchar(255) NOT NULL,
    title text NOT NULL,
    sub_title text,
    description text,
    first_publication_date varchar(255),
    publication_date_epoch bigint,
    isbn_ten varchar(20),
    isbn_thirteen varchar(20),
    language_code varchar(50),
    num_of_pages integer,
    ol_id varchar(100),
    cover_id bigint,
    featured_covers jsonb,
    series text,
    position_in_series varchar(100),
    reading_id varchar(255),
    prh_id varchar(255),
    goodreads_resolved boolean NOT NULL DEFAULT false,
    google_resolved boolean NOT NULL DEFAULT false,
    featured_edition_fk bigint
);

CREATE TABLE work_external_identifier (
    work_id bigint NOT NULL,
    provider varchar(50) NOT NULL,
    external_id varchar(255) NOT NULL,
    is_canonical boolean NOT NULL
);

CREATE TABLE work_cover (
    work_id bigint NOT NULL,
    cover_id bigint NOT NULL,
    position integer
);

CREATE TABLE work_cover_urls (
    work_id bigint NOT NULL,
    url text NOT NULL,
    provider varchar(50) NOT NULL
);

CREATE TABLE work_contributor (
    work_id bigint NOT NULL,
    creator_id bigint NOT NULL,
    role_code varchar(100),
    role_description varchar(255),
    display text,
    primary_flag boolean,
    observed_isbns jsonb,
    provider varchar(50) NOT NULL
);

CREATE TABLE prh_work_metadata (
    work_id bigint NOT NULL,
    prh_work_id bigint NOT NULL,
    prh_display_title text,
    prh_url text,
    keynote_html text,
    positioning_html text,
    awards jsonb,
    frontlistiest_isbn varchar(20),
    isbn_counts jsonb
);

CREATE TABLE work_editions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    work_id bigint NOT NULL,
    uuid varchar(255) NOT NULL,
    isbn_ten varchar(20),
    isbn_thirteen varchar(20),
    publication_date text,
    publication_year varchar(20),
    ol_id varchar(100),
    number_of_pages varchar(50),
    lccn varchar(100),
    oclc_number varchar(100),
    publisher text,
    series text,
    goodreads_id varchar(100),
    google_id varchar(100),
    asin varchar(50)
);

CREATE TABLE edition_external_identifier (
    edition_id bigint NOT NULL,
    provider varchar(50) NOT NULL,
    external_id varchar(255) NOT NULL,
    is_canonical boolean NOT NULL
);

CREATE TABLE edition_identifier (
    edition_id bigint NOT NULL,
    identifier_type varchar(50) NOT NULL,
    identifier varchar(255) NOT NULL,
    normalized_identifier varchar(255),
    position integer
);

CREATE TABLE edition_publisher (
    edition_id bigint NOT NULL,
    publisher text NOT NULL,
    position integer
);

CREATE TABLE edition_cover (
    edition_id bigint NOT NULL,
    cover_id bigint NOT NULL,
    position integer
);

CREATE TABLE edition_language (
    edition_id bigint NOT NULL,
    language_code varchar(100) NOT NULL,
    position integer
);

CREATE TABLE prh_edition_metadata (
    edition_id bigint NOT NULL,
    prh_work_id bigint NOT NULL,
    isbn varchar(20),
    trim_size varchar(255),
    format_family varchar(255),
    format_code varchar(100),
    format_name varchar(255),
    version text,
    imprint_code varchar(100),
    imprint_name text,
    asin varchar(50),
    cover_url text,
    prh_url text,
    series_code varchar(100),
    series_name text,
    series_position varchar(100),
    custom_subject_category text,
    sales_restriction text,
    raw_flags jsonb
);

CREATE TABLE search_tag (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    tag_name varchar(1000) NOT NULL,
    prevalence bigint NOT NULL,
    weight double precision NOT NULL
);

CREATE TABLE work_creators (
    work_id bigint NOT NULL,
    creator_id bigint NOT NULL
);

CREATE TABLE edition_creators (
    edition_id bigint NOT NULL,
    creator_id bigint NOT NULL
);

CREATE TABLE work_tags (
    work_id bigint NOT NULL,
    tag_id bigint NOT NULL
);

CREATE TABLE work_tag_source (
    work_id bigint NOT NULL,
    tag_id bigint NOT NULL,
    provider varchar(50) NOT NULL,
    tag_source varchar(50) NOT NULL
);

CREATE TABLE book_series (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    uuid varchar(255) NOT NULL,
    prh_series_code varchar(100) NOT NULL,
    name text,
    description_html text,
    series_count bigint,
    series_date varchar(100),
    is_numbered boolean,
    is_kids boolean,
    prh_url text
);

CREATE TABLE series_external_identifier (
    series_id bigint NOT NULL,
    provider varchar(50) NOT NULL,
    external_id varchar(255) NOT NULL,
    is_canonical boolean NOT NULL
);

CREATE TABLE work_series (
    work_id bigint NOT NULL,
    series_id bigint NOT NULL,
    position varchar(100)
);

CREATE TABLE author_tag_profile (
    author_id bigint NOT NULL,
    tag_id bigint NOT NULL,
    work_count bigint NOT NULL,
    catalog_share double precision NOT NULL,
    profile_weight double precision NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE TABLE author_profile_state (
    author_id bigint NOT NULL,
    tagged_work_count bigint NOT NULL,
    profile_hash varchar(32) NOT NULL,
    similarity_profile_hash varchar(32) NOT NULL,
    profile_generated_at timestamptz NOT NULL,
    similarity_generated_at timestamptz NOT NULL,
    algorithm_version varchar(100) NOT NULL
);

CREATE TABLE similar_author (
    author_id bigint NOT NULL,
    similar_author_id bigint NOT NULL,
    similarity_score double precision NOT NULL,
    shared_tag_count integer NOT NULL,
    shared_tags jsonb NOT NULL,
    rank integer NOT NULL,
    generated_at timestamptz NOT NULL
);

CREATE TABLE author_profile_refresh_queue (
    author_id bigint NOT NULL,
    queued_at timestamptz NOT NULL DEFAULT now(),
    claimed_at timestamptz,
    attempts integer NOT NULL DEFAULT 0,
    last_failure text
);

CREATE TABLE work_merge_audit (
    source_work_a varchar(255) NOT NULL,
    source_work_b varchar(255) NOT NULL,
    match_rule varchar(100) NOT NULL,
    confidence double precision NOT NULL,
    evidence jsonb NOT NULL
);

CREATE TABLE work_merge_candidate (
    source_work_a varchar(255) NOT NULL,
    source_work_b varchar(255) NOT NULL,
    match_rule varchar(100) NOT NULL,
    confidence double precision NOT NULL,
    evidence jsonb NOT NULL
);

CREATE TABLE author_merge_audit (
    source_author_a varchar(255) NOT NULL,
    source_author_b varchar(255) NOT NULL,
    match_rule varchar(100) NOT NULL,
    confidence double precision NOT NULL,
    evidence jsonb NOT NULL
);

CREATE TABLE author_merge_candidate (
    normalized_name text NOT NULL,
    source_author_count bigint NOT NULL,
    sample_source_keys jsonb NOT NULL,
    match_rule varchar(100) NOT NULL,
    confidence double precision NOT NULL,
    evidence jsonb NOT NULL
);
